matrix:
  include:
    - language: c
      before_script:
        - cd $TRAVIS_BUILD_DIR/c
      script:
        - make

    - language: go
      install: |
          go get -t -v go/...
      before_script:
        - cd $TRAVIS_BUILD_DIR/go
      script:
        - make

    - language: ruby
      before_script:
        - cd $TRAVIS_BUILD_DIR/ruby
      script:
        - make

    - language: java
      jdk:
         - oraclejdk8
      before_script:
        - cd $TRAVIS_BUILD_DIR/java
      script:
        - make

    - language: rust
      before_script:
        - cd $TRAVIS_BUILD_DIR/rust
      script:
        - make

    - language: lua
      before_script:
        - cd $TRAVIS_BUILD_DIR/lua
      script:
        - make

    - language: haskell
      install: |
          cd $TRAVIS_BUILD_DIR/haskell;cabal install
      before_script:
        - cd $TRAVIS_BUILD_DIR/haskell
      script:
        - make
