matrix:
  include:
    - language: c
      before_script:
        - cd c
      script:
        - make

    - language: go
      install: |
          go get -t -v go/...
      before_script:
        - cd go
      script:
        - make

    - language: ruby
      before_script:
        - cd ruby
      script:
        - make

    - language: jdk
      before_script:
        - cd java
      script:
        - make

    - language: rust
      before_script:
        - cd rust
      script:
        - make

    - language: lua
      before_script:
        - cd lua
      script:
        - make

    - language: haskell
      before_script:
        - cd haskell
      script:
        - make
