matrix:
  include:
    - language: c
      before_script:
        - cd c
      script:
        - make

    - language: ruby
      before_script:
        - cd ruby
      script:
        - make

    - language: java
      before_script:
        - cd java
      script:
        - make

    - language: rust
      before_script:
        - cd rust
      script:
        - make

    - language: lua
      before_script:
        - cd lua
      script:
        - make

    - language: haskell
      before_script:
        - cd haskell
      script:
        - make
