#language: "c" "go" "java" "lua" "haskell" "ruby"

matrix:
  include:
    - language: c
      before_script:
        - cd c
      script:
        - make

    - language: ruby
      before_script:
        - cd ruby
      script:
        - make

    - language: java
      before_script:
        - cd java
      script:
        - make
